### ISSUE TITLE
Problème barre de défilement 2

### ISSUE THREAD

**Issue by AlexDmr** [PROJET-TER-MITTON-PINARD/lib-basic-linechart#2]
Lorsqu'on dézoome et qu'on scrolle avec la barre de défilement, on a tendance à perdre le focus.

Testé sur la page exemple.

**Comment by cedricoco** [comment]
Problème réglé avec le patch 0.9.3

**Comment by AlexDmr** [comment]
Le problème n'est réglé que si le curseur reste dans le cadre du graphique mais on perd le focus si on en sort.
=> Il faut s'abonner au niveau de la page ou de la fenêtre
ex: avec fromEvent(window, 'pointermove')  qui vous renvoie un observable adéquat auquel il faut s'abonner si et seulement si on est en train de faire défiler la barre.
