### ISSUE TITLE
Problème de zoom

### ISSUE THREAD

**Issue by AlexDmr** [PROJET-TER-MITTON-PINARD/lib-basic-linechart#3]
On zoom trop rapidement => proposer un réglage avec une valeur par défaut ?
Autre problème : on zoom quand on veut faire défiler la page => Utiliser la touhe control + molette pour faire le zoom, de sorte à conserver la molette seule pour le défilement de la page

**Comment by cedricoco** [comment]
Problème réglé avec le patch 0.9.3, on peut maintenant définir une vitesse de zoom entre 0 et 1. 0,2 par défaut. (Avant c'était 0,5 par défaut)
