### ISSUE TITLE
Problème perte de focus 2

### ISSUE THREAD

**Issue by AlexDmr** [PROJET-TER-MITTON-PINARD/lib-basic-linechart#4]
Le problème n'est réglé que si le curseur reste dans le cadre du graphique mais on perd le focus si on en sort.
=> Il faut s'abonner au niveau de la page ou de la fenêtre
ex: avec fromEvent(window, 'pointermove') qui vous renvoie un observable adéquat auquel il faut s'abonner si et seulement si on est en train de faire défiler la barre.

**Comment by cedricoco** [comment]
C'est noté. Nous prenons en compte votre remarque pour la prochaine version.

**Comment by cedricoco** [comment]
Problème réglé.
